// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD29iaNqJGgkLXx2FLuJHz0grqqch9Yd4k',
    appId: '1:916224851549:web:2f812c8fb38ab48b2d17b4',
    messagingSenderId: '916224851549',
    projectId: 'garaage-14d0c',
    authDomain: 'garaage-14d0c.firebaseapp.com',
    storageBucket: 'garaage-14d0c.appspot.com',
    measurementId: 'G-0T72THKHV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJdcuhekojE4Ejg0MnV0olpYEENh59iiA',
    appId: '1:916224851549:android:d2f72319ce720c632d17b4',
    messagingSenderId: '916224851549',
    projectId: 'garaage-14d0c',
    storageBucket: 'garaage-14d0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI1CacwsUhv1V8mdEQ1KmnXwByRAJWP64',
    appId: '1:916224851549:ios:b3f6fa4d5138c75e2d17b4',
    messagingSenderId: '916224851549',
    projectId: 'garaage-14d0c',
    storageBucket: 'garaage-14d0c.appspot.com',
    iosBundleId: 'com.example.garaage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI1CacwsUhv1V8mdEQ1KmnXwByRAJWP64',
    appId: '1:916224851549:ios:b3f6fa4d5138c75e2d17b4',
    messagingSenderId: '916224851549',
    projectId: 'garaage-14d0c',
    storageBucket: 'garaage-14d0c.appspot.com',
    iosBundleId: 'com.example.garaage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD29iaNqJGgkLXx2FLuJHz0grqqch9Yd4k',
    appId: '1:916224851549:web:49e9f791b79f8b002d17b4',
    messagingSenderId: '916224851549',
    projectId: 'garaage-14d0c',
    authDomain: 'garaage-14d0c.firebaseapp.com',
    storageBucket: 'garaage-14d0c.appspot.com',
    measurementId: 'G-X9REM0Z8B7',
  );

}